data: /data1/gauku/lowresource_mt/hin/data/hin
save_model: /data1/gauku/lowresource_mt/hin/models/hin_fasttext_embeddings_transformer/hin_fasttext_transformer
layers: 6
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
heads: 8
encoder_type: transformer
decoder_type: transformer
position_encoding: 'true'
train_steps: 5000
max_generator_batches: 2
dropout: 0.1
batch_size: 4096
batch_type: tokens
normalization: tokens
accum_count: 2
optim: adam
adam_beta2: 0.998
decay_method: noam
warmup_steps: 8000
learning_rate: 2
max_grad_norm: 0
param_init: 0
param_init_glorot: 'true'
label_smoothing: 0.1

#valid_steps: 10000
valid_steps: 111
report_every: 111
save_checkpoint_steps: 111

pre_word_vecs_enc: /data1/gauku/lowresource_mt/hin/data/embeddings.enc.pt
pre_word_vecs_dec: /data1/gauku/lowresource_mt/hin/data/embeddings.dec.pt

tensorboard: 'true'

world_size: 1
gpu_ranks:
- 0
